// ============================================================================
//  font_rom.sv  —  8x16 ASCII bitmap font ROM (inferred M10K)
// ----------------------------------------------------------------------------
//  Standard IBM-PC style 8x16 character glyphs. 256 glyphs x 16 rows = 4096
//  bytes; printable ASCII 0x20..0x7E are populated, all other codes are blank
//  (so a stray control code renders as empty space rather than garbage).
//
//  ADDRESS  = { char[7:0], row[3:0] }  == char*16 + row   (12 bits, 0..4095)
//  DATA     = 8-pixel row bitmap; MSB (bit 7) = LEFTMOST pixel on screen.
//             A '1' bit is a glyph (foreground) pixel.
//
//  The ROM is initialised from font.mif (generated by gen_font_mif.py). The
//  read is registered so Quartus infers a Cyclone V M10K block. RESET: none —
//  ROM contents come from the .mif; omitting a reset is what enables clean
//  M10K inference.
// ============================================================================

module font_rom (
    input  logic        clk,
    input  logic [11:0] addr,           // {char, row}
    output logic [7:0]  data            // registered row bitmap
);

    // Inferred block ROM, initialised from the Quartus .mif file.
    (* ram_init_file = "font.mif", ramstyle = "M10K" *)
    logic [7:0] rom [0:4095];

    // Init-file handling — exactly ONE mechanism is active per tool:
    //   * Synthesis (Quartus): ALTERA_RESERVED_QIS is defined, so the
    //     $readmemh below is excluded and the ram_init_file attribute loads
    //     font.mif into the M10K.
    //   * Simulation (ModelSim/Questa/Icarus): the attribute is ignored, so
    //     $readmemh loads font.hex. gen_font_mif.py emits both files from the
    //     identical 4096-byte image, so the two paths are equivalent.
    `ifndef ALTERA_RESERVED_QIS
    initial begin
        $readmemh("font.hex", rom);
    end
    `endif

    always_ff @(posedge clk) begin
        data <= rom[addr];
    end

endmodule
