// ============================================================================
//  font_rom.sv  —  8x16 ASCII bitmap font ROM (inferred M10K)
// ----------------------------------------------------------------------------
//  Standard IBM-PC style 8x16 character glyphs. 256 glyphs x 16 rows = 4096
//  bytes; printable ASCII 0x20..0x7E are populated, all other codes are blank
//  (so a stray control code renders as empty space rather than garbage).
//
//  ADDRESS  = { char[7:0], row[3:0] }  == char*16 + row   (12 bits, 0..4095)
//  DATA     = 8-pixel row bitmap; MSB (bit 7) = LEFTMOST pixel on screen.
//             A '1' bit is a glyph (foreground) pixel.
//
//  The ROM is initialised from font.mif (generated by gen_font_mif.py). The
//  read is registered so Quartus infers a Cyclone V M10K block. RESET: none —
//  ROM contents come from the .mif; omitting a reset is what enables clean
//  M10K inference.
// ============================================================================

module font_rom (
    input  logic        clk,
    input  logic [11:0] addr,           // {char, row}
    output logic [7:0]  data            // registered row bitmap
);

    // Inferred Cyclone V M10K block ROM.
    //
    //  romstyle = "M10K" : force the array into block ROM (M10K), not LABs.
    //                      ('romstyle' is the correct attribute for a ROM;
    //                       'ramstyle' is for RAM and is not honoured here.)
    //
    //  The array has NO reset — M10K has no reset on contents or output reg, so
    //  a reset branch would block block-ROM inference and push it into registers.
    (* romstyle = "M10K" *)
    logic [7:0] rom [0:4095];

    // Initialise the ROM image from font.hex. A plain initial-block $readmemh is
    // the canonical Quartus inferred-ROM pattern: Quartus honours it as the
    // synthesis-time memory initialisation, and every simulator (ModelSim/
    // Questa/Icarus) honours it too — so ONE mechanism covers both flows and
    // there is no .mif-vs-$readmemh dual-init conflict.
    //
    //   * font.hex is generated by gen_font_mif.py (one hex byte per line).
    //   * font.mif (same 4096-byte image) is also generated and kept as a
    //     deliverable, e.g. for an explicit altsyncram/IP instantiation; it is
    //     intentionally NOT referenced here to keep a single init source.
    initial begin
        $readmemh("font.hex", rom);
    end

    always_ff @(posedge clk) begin
        data <= rom[addr];
    end

endmodule
