#!/usr/bin/env python3
# ============================================================================
#  gen_font_mif.py  —  generate font.mif (+ font.hex) for font_rom.sv
# ----------------------------------------------------------------------------
#  Builds a 4096-byte 8x16 ASCII font image:  256 glyphs x 16 rows.
#  Address = char*16 + row ; byte = one 8-pixel row, MSB = leftmost pixel.
#
#  Printable ASCII 0x20..0x7E are populated from the authentic IBM/VGA 8x16
#  console font (Lat15-VGA16.psf, shipped with the kbd console-data package);
#  every other code is left blank so a stray control byte renders as a space
#  rather than garbage.
#
#  Outputs (both describe the identical 4096-byte image):
#    * font.mif  — Quartus memory-init file (used by synthesis via
#                  font_rom.sv's ram_init_file attribute)
#    * font.hex  — one hex byte per line (used by $readmemh in simulation)
#
#  If the PSF font cannot be found, the script falls back to rendering the
#  glyphs with Pillow + DejaVuSansMono so it still produces a usable font.
#
#  Usage:   python3 gen_font_mif.py
# ============================================================================

import gzip
import os
import struct
import sys

DEPTH = 4096          # 256 chars * 16 rows
WIDTH = 8             # bits per row

PSF_CANDIDATES = [
    "/usr/share/consolefonts/Lat15-VGA16.psf.gz",
    "/usr/share/consolefonts/Lat2-VGA16.psf.gz",
    "/usr/share/consolefonts/Lat38-VGA16.psf.gz",
    "/usr/share/kbd/consolefonts/Lat15-VGA16.psf.gz",
]


def load_psf_glyphs(path):
    """Return list of 256 glyphs, each a list of 16 row-bytes (8 px wide)."""
    raw = gzip.open(path, "rb").read() if path.endswith(".gz") else open(path, "rb").read()

    # PSF1: magic 0x36 0x04
    if raw[0] == 0x36 and raw[1] == 0x04:
        mode, charsize = raw[2], raw[3]
        nchars = 512 if (mode & 0x01) else 256
        glyphs = raw[4:]
        if charsize != 16:
            raise ValueError(f"PSF1 charsize {charsize} != 16")
    # PSF2: magic 0x72 0xB5 0x4A 0x86
    elif raw[:4] == b"\x72\xb5\x4a\x86":
        (ver, hdrsize, flags, nchars, charsize,
         height, width) = struct.unpack("<IIIIIII", raw[4:32])
        if height != 16 or width != 8:
            raise ValueError(f"PSF2 glyph {width}x{height} != 8x16")
        glyphs = raw[hdrsize:]
    else:
        raise ValueError("not a PSF1/PSF2 file")

    out = []
    for c in range(256):
        base = c * 16
        rows = list(glyphs[base:base + 16])
        if len(rows) < 16:
            rows += [0] * (16 - len(rows))
        out.append(rows)
    return out


def render_with_pillow():
    """Fallback: rasterise printable ASCII with a monospace TTF into 8x16."""
    from PIL import Image, ImageDraw, ImageFont
    ttf = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
    font = ImageFont.truetype(ttf, 16)
    glyphs = [[0] * 16 for _ in range(256)]
    for code in range(0x20, 0x7F):
        img = Image.new("1", (WIDTH, 16), 0)
        d = ImageDraw.Draw(img)
        d.text((0, -2), chr(code), fill=1, font=font)
        rows = []
        for y in range(16):
            byte = 0
            for x in range(WIDTH):
                if img.getpixel((x, y)):
                    byte |= 1 << (7 - x)
            rows.append(byte)
        glyphs[code] = rows
    return glyphs


def build_image():
    for p in PSF_CANDIDATES:
        if os.path.exists(p):
            try:
                glyphs = load_psf_glyphs(p)
                # Blank everything outside printable ASCII for a clean buffer.
                for c in list(range(0x00, 0x20)) + list(range(0x7F, 0x100)):
                    glyphs[c] = [0] * 16
                print(f"font source: {p}")
                return glyphs
            except Exception as e:  # pragma: no cover
                print(f"  skip {p}: {e}", file=sys.stderr)
    print("font source: Pillow/DejaVuSansMono fallback")
    return render_with_pillow()


def write_outputs(glyphs):
    data = []
    for c in range(256):
        data.extend(glyphs[c][r] & 0xFF for r in range(16))
    assert len(data) == DEPTH

    # font.hex — one byte per line (simulation $readmemh)
    with open("font.hex", "w") as f:
        for b in data:
            f.write(f"{b:02X}\n")

    # font.mif — Quartus memory init (synthesis)
    with open("font.mif", "w") as f:
        f.write("-- 8x16 ASCII font ROM  (generated by gen_font_mif.py)\n")
        f.write("-- addr = char*16 + row ; data = 8-px row, MSB = leftmost pixel\n")
        f.write(f"WIDTH={WIDTH};\n")
        f.write(f"DEPTH={DEPTH};\n")
        f.write("ADDRESS_RADIX=HEX;\n")
        f.write("DATA_RADIX=HEX;\n")
        f.write("CONTENT BEGIN\n")
        for addr, b in enumerate(data):
            f.write(f"    {addr:03X} : {b:02X};\n")
        f.write("END;\n")

    print(f"wrote font.mif and font.hex ({DEPTH} bytes)")


if __name__ == "__main__":
    write_outputs(build_image())
